apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ upper .Release.Name }}
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ upper .Release.Name }}
  {{- with .Values.service }}
    {{- toYaml . | nindent 2 }}
  {{- end }}