apiVersion: v1
kind: Service
metadata:
  labels:
    app: zbx-server-mysql
  name: zbx-server-mysql-service
spec:
  selector:
    app: zbx-server-mysql
  type: ClusterIP  
  ports:
  - port: 10051
    targetPort: 10051